version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrapestation_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app

  redis:
    image: "redis:latest"
    container_name: scrapestation_redis
    ports:
      - "6379:6379"
